# Generated by Django 5.1.2 on 2024-11-03 17:55

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Storage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',  # Updated to correct model name
            old_name='capacity',
            new_name='storage_capacity',
        ),
        migrations.RenameField(
            model_name='storage',  # Updated to correct model name
            old_name='description',
            new_name='storage_description',
        ),
        migrations.RenameField(
            model_name='storage',  # Updated to correct model name
            old_name='manufacturer',
            new_name='storage_manufacturer',
        ),
        migrations.RenameField(
            model_name='storage',  # Updated to correct model name
            old_name='name',
            new_name='storage_name',
        ),
        migrations.RenameField(
            model_name='storage',  # Updated to correct model name
            old_name='storage_type',
            new_name='storage_storage_type',
        ),
        migrations.RenameField(
            model_name='storagerecomendedbuild',  # Updated to correct model name
            old_name='id_storage',
            new_name='storage_id',
        ),
    ]
