# Generated by Django 5.1.3 on 2024-11-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cpu_app', '0004_rename_cpu_socket_cpu_cpu_main_cpu_socket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cpu_main',
            new_name='CpuMain',
        ),
    ]
