# Generated by Django 5.1.2 on 2024-11-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Powersupply_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PowerSupply',
            new_name='PowerSupply_main',
        ),
    ]
