# Generated by Django 5.1.2 on 2024-11-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coolingsystem_app', '0002_rename_coolingsystem_coolingsystem_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coolingsystem_main',
            old_name='description',
            new_name='coolingsystem_description',
        ),
        migrations.RenameField(
            model_name='coolingsystem_main',
            old_name='form_factor',
            new_name='coolingsystem_form_factor',
        ),
        migrations.RenameField(
            model_name='coolingsystem_main',
            old_name='manufacturer',
            new_name='coolingsystem_manufacturer',
        ),
        migrations.RenameField(
            model_name='coolingsystem_main',
            old_name='name',
            new_name='coolingsystem_name',
        ),
        migrations.RenameField(
            model_name='coolingsystem_main',
            old_name='tdp',
            new_name='coolingsystem_tdp',
        ),
    ]
