# Generated by Django 5.1.3 on 2024-11-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motherboard_app', '0003_rename_description_motherboard_main_motherboard_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motherboard_main',
            new_name='MotherboardMain',
        ),
    ]
