# Generated by Django 5.1.3 on 2024-11-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case_app', '0003_rename_description_case_main_case_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case_main',
            new_name='CaseMain',
        ),
    ]
