# Generated by Django 5.1.3 on 2024-11-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coolingsystem_app', '0003_rename_description_coolingsystem_main_coolingsystem_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoolingSystem_main',
            new_name='CoolingSystemMain',
        ),
    ]
