# Generated by Django 5.1.3 on 2024-11-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendedbuild_app', '0002_rename_recommendedbuild_recommendedbuild_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedBuild_main',
            new_name='RecommendedBuildMain',
        ),
    ]
