# Generated by Django 5.1.2 on 2024-11-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Powersupply_app', '0002_rename_powersupply_powersupply_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powersupply_main',
            old_name='description',
            new_name='powersupply_description',
        ),
        migrations.RenameField(
            model_name='powersupply_main',
            old_name='manufacturer',
            new_name='powersupply_manufacturer',
        ),
        migrations.RenameField(
            model_name='powersupply_main',
            old_name='name',
            new_name='powersupply_name',
        ),
        migrations.RenameField(
            model_name='powersupply_main',
            old_name='power',
            new_name='powersupply_power',
        ),
    ]
