# Generated by Django 5.1.3 on 2024-11-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Powersupply_app', '0003_rename_description_powersupply_main_powersupply_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PowerSupply_main',
            new_name='PowerSupplyMain',
        ),
    ]
