# Generated by Django 5.1.2 on 2024-11-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gpu_app', '0002_rename_gpu_gpu_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu_main',
            old_name='description',
            new_name='gpu_description',
        ),
        migrations.RenameField(
            model_name='gpu_main',
            old_name='manufacturer',
            new_name='gpu_manufacturer',
        ),
        migrations.RenameField(
            model_name='gpu_main',
            old_name='name',
            new_name='gpu_name',
        ),
        migrations.RenameField(
            model_name='gpu_main',
            old_name='Ram_app',
            new_name='gpu_ram',
        ),
        migrations.RenameField(
            model_name='gpu_main',
            old_name='ram_type',
            new_name='gpu_ram_type',
        ),
        migrations.RenameField(
            model_name='gpu_main',
            old_name='series',
            new_name='gpu_series',
        ),
    ]
