# Generated by Django 5.1.3 on 2024-11-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gpu_app', '0003_rename_description_gpu_main_gpu_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gpu_main',
            new_name='GpuMain',
        ),
    ]
