# Generated by Django 5.1.2 on 2024-11-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case_app', '0002_rename_case_case_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_main',
            old_name='description',
            new_name='case_description',
        ),
        migrations.RenameField(
            model_name='case_main',
            old_name='fan_place',
            new_name='case_fan_place',
        ),
        migrations.RenameField(
            model_name='case_main',
            old_name='form_factor',
            new_name='case_form_factor',
        ),
        migrations.RenameField(
            model_name='case_main',
            old_name='manufacturer',
            new_name='case_manufacturer',
        ),
        migrations.RenameField(
            model_name='case_main',
            old_name='name',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='case_main',
            old_name='power_supply',
            new_name='case_power_supply',
        ),
    ]
