# Generated by Django 5.1.3 on 2024-11-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ram_app', '0004_rename_ram_ram_amount_ram_main_ram_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ram_main',
            new_name='RamMain',
        ),
        migrations.DeleteModel(
            name='RamRecomendedBuild',
        ),
    ]
