# Generated by Django 5.1.3 on 2024-11-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage_app', '0002_rename_capacity_storage_storage_capacity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='StorageMain',
        ),
        migrations.DeleteModel(
            name='StorageRecomendedBuild',
        ),
    ]
